"""On-demand resume drafting, driven by GitHub issues.

The dashboard's ✍️ link on each row opens a pre-filled issue titled
"draft: <title> @ <company>" labeled `draft-request`. Each run:

1. reads open draft-request issues (workflow GITHUB_TOKEN),
2. matches each to a tracked posting (freshest fetch first, for the full
   description; falls back to the state record),
3. drafts the resume via triage.draft_resumes (library-only hard rules),
4. comments the draft's link on the issue and closes it.

Anything the requester typed in the issue body is passed to the drafter
as emphasis notes. No auto-drafting happens anywhere else.
"""
import logging
import os
import re

import requests

from . import triage
from .models import Job
from .util import company_key, title_key

log = logging.getLogger(__name__)

API = "https://api.github.com"


def _gh(token: str) -> dict:
    return {"Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json"}


def _find_job(title: str, company: str, raw_jobs: list[Job], seen: dict) -> Job | None:
    want = (company_key(company), title_key(title))
    for j in raw_jobs:  # fresh fetch first: has descriptions
        if (company_key(j.company), title_key(j.title)) == want:
            return j
    for r in seen.values():
        if (company_key(r.get("company", "")), title_key(r.get("title", ""))) == want:
            return Job(title=r["title"], company=r["company"], location=r["location"],
                       url=r["url"], source=r["source"])
    return None


def process(raw_jobs: list[Job], seen: dict, config: dict) -> list:
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo:
        log.info("No GITHUB_TOKEN; skipping draft requests.")
        return []
    resp = requests.get(f"{API}/repos/{repo}/issues",
                        params={"labels": "draft-request", "state": "open",
                                "per_page": 20},
                        headers=_gh(token), timeout=30)
    resp.raise_for_status()
    drafts = []
    branch = os.environ.get("GITHUB_REF_NAME", "claude/brainstorm-approach-8qukjx")
    for issue in resp.json():
        m = re.match(r"draft:\s*(.+?)\s*@\s*(.+)", issue.get("title", ""), re.I)
        if not m:
            continue
        title, company = m.group(1), m.group(2)
        job = _find_job(title, company, raw_jobs, seen)
        number = issue["number"]
        if job is None:
            _comment(token, repo, number,
                     "Couldn't match this posting to a tracked job — it may "
                     "have closed. Ask in the repo if it should exist.")
            continue
        notes = (issue.get("body") or "").strip()
        if notes:
            job.description += f"\n\nREQUESTER EMPHASIS NOTES (honor these): {notes[:800]}"
        written = triage.draft_resumes(
            [job], {job.job_id: {"score": 100}}, threshold=0)
        if written:
            path = written[0]
            drafts.append(path)
            _comment(token, repo, number,
                     f"Draft ready: [{path.name}]"
                     f"(https://github.com/{repo}/blob/{branch}/{path})")
            _close(token, repo, number)
        else:
            _comment(token, repo, number,
                     "Draft failed (library not ready or model error) — "
                     "see the Actions log for this run.")
    return drafts


def _comment(token: str, repo: str, number: int, text: str) -> None:
    body = f"{text}\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
    requests.post(f"{API}/repos/{repo}/issues/{number}/comments",
                  json={"body": body}, headers=_gh(token), timeout=30)


def _close(token: str, repo: str, number: int) -> None:
    requests.patch(f"{API}/repos/{repo}/issues/{number}",
                   json={"state": "closed"}, headers=_gh(token), timeout=30)
